### ISSUE TITLE
Got a license for this?

### ISSUE THREAD

**Issue by mlippert** [manuelstofer/json-pointer#15]
Very nice implementation, clean, useful methods, well documented.

I was wondering if you had a license in mind because I'd like to copy this code into my client side google closure library and tweak it to match the style and namespacing there, if it'd be OK. I would of course leave a comment in the file back to this repo as the original source.

**Comment by manuelstofer** [comment]
Thank you! 
Sure, you can use and tweak it. Pick any Open Source license like MIT, BSD or GPL.
